# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3883d1c5fc2de1e546dddb3552b7cffeefb945036f952a6d89f117e06aadb2185ec060d51aa3b5d5849e41756af124e7d5676207b374a9783f091829380d8f4f

test:
  secret_key_base: 229a0cdaea14e4f67ed9018953a6f357f7fd0438db8c736adf61ded189ba27564fd33721c48fbcba607248b2364c787a4b120dae94e67e5e672674ec7fb112b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
